// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttfgieddnljwhjqnckep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZmdpZWRkbmxqd2hqcW5ja2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzIxMjgsImV4cCI6MjA2NDAwODEyOH0.iiZxSYvmZshxWusUhyOavhmur-Gw9015nXWGXtTqGDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);